apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lab-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
      description: "The URL of the repository to clone"
    - name: branch
      type: string
      default: "main"
    - name: build-image
      type: string
    - name: app-name
      type: string
      default: "counter-app"
  tasks:
    # Task 1: Cleanup
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 2: Clone repository
    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 3: Lint
    - name: lint
      taskRef:
        name: eslint
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 4: Test
    - name: tests
      taskRef:
        name: jest-test
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 5: Build Image
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: "$(params.build-image)"
        - name: CONTEXT
          value: "."
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 6: Deploy
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -

