apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lab-pipeline-simple
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
      description: "The URL of the repository to clone"
    - name: branch
      type: string
      default: "main"
    - name: build-image
      type: string
    - name: app-name
      type: string
      default: "counter-app"
  tasks:
    # Task 1: Clone repository
    - name: clone
      taskRef:
        name: git-clone-repo
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 2: Lint
    - name: lint
      taskRef:
        name: npm-lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 3: Test
    - name: test
      taskRef:
        name: npm-test
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 4: Build Image
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - test
      params:
        - name: IMAGE
          value: "$(params.build-image)"
      workspaces:
        - name: source
          workspace: shared-workspace

    # Task 5: Deploy
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -

