---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-repo
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: revision
      type: string
      description: Git revision (branch/tag/commit)
      default: "main"
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "Cloning Repository"
        echo "=========================================="
        echo "Repository: $(params.repo-url)"
        echo "Revision: $(params.revision)"
        echo ""
        
        # Clone the repository
        git clone --branch $(params.revision) --depth 1 $(params.repo-url) repo
        cd repo
        
        echo "✅ Repository cloned successfully"
        echo ""
        echo "Files in repository:"
        ls -la
        echo ""

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: install-and-lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)/repo
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "Installing Dependencies & Linting"
        echo "=========================================="
        echo "Current directory: $(pwd)"
        echo ""
        
        if [ ! -f "package.json" ]; then
          echo "❌ ERROR: package.json not found!"
          exit 1
        fi
        
        echo "📦 Installing dependencies..."
        npm install
        
        echo ""
        echo "🔍 Running ESLint..."
        npm run lint
        
        echo "✅ Linting passed!"
        echo ""

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:20-alpine
      workingDir: $(workspaces.source.path)/repo
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "Running Tests"
        echo "=========================================="
        
        echo "🧪 Running Jest tests..."
        npm test
        
        echo "✅ Tests passed!"
        echo ""

