---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        echo "=========================================="
        echo "Cleaning Workspace"
        echo "=========================================="
        echo "Workspace path: $(workspaces.source.path)"
        echo ""
        
        # Remove all files from workspace
        if [ -d "$(workspaces.source.path)" ]; then
          rm -rf $(workspaces.source.path)/* 2>/dev/null || true
          rm -rf $(workspaces.source.path)/.[!.]* 2>/dev/null || true
          rm -rf $(workspaces.source.path)/..?* 2>/dev/null || true
          echo "✅ Workspace cleaned"
        else
          echo "✅ Workspace already empty"
        fi
        echo ""

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: revision
      type: string
      description: Git revision (branch/tag/commit)
      default: "main"
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "Cloning Repository"
        echo "=========================================="
        echo "Repository: $(params.repo-url)"
        echo "Revision: $(params.revision)"
        echo ""
        
        # Clone directly to workspace root (not subdirectory)
        git clone --branch $(params.revision) --depth 1 $(params.repo-url) .
        
        echo "✅ Repository cloned successfully"
        echo ""
        echo "Files in repository:"
        ls -la
        echo ""

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to ESLint
      type: string
      default: "src/ tests/ --ext *.js"
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "ESLint - Installing Dependencies & Linting"
        echo "=========================================="
        echo "Current directory: $(pwd)"
        echo ""
        
        if [ ! -f "package.json" ]; then
          echo "❌ ERROR: package.json not found!"
          echo "Directory contents:"
          ls -la
          exit 1
        fi
        
        echo "📦 Installing dependencies..."
        npm install
        
        echo ""
        echo "🔍 Running ESLint..."
        npm run lint $(params.args)
        
        echo "✅ Linting passed!"
        echo ""

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to jest
      type: string
      default: "-v"
  steps:
    - name: test
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "=========================================="
        echo "Jest - Running Tests"
        echo "=========================================="
        echo "Current directory: $(pwd)"
        echo ""
        
        if [ ! -f "package.json" ]; then
          echo "❌ ERROR: package.json not found!"
          echo "Directory contents:"
          ls -la
          exit 1
        fi
        
        echo "🧪 Running Jest tests..."
        npm test $(params.args)
        
        echo "✅ Tests passed!"
        echo ""

